#!/bin/bash

# Start the run once job.
echo "Docker container has been started"

declare -p TESTVAR SECRET pickles > /container.env

# Setup a cron schedule
echo "SHELL=/bin/bash
BASH_ENV=/container.env
* * * * * /runme >> /var/log/cron.log 2>&1
# This extra line makes it a valid cron" > scheduler.txt

touch /var/log/cron.log
crontab scheduler.txt
cron -f
